DROP TABLE DELAYS CASCADE CONSTRAINTS;
DROP TABLE AIRLINE_AIRPORT CASCADE CONSTRAINTS;
DROP TABLE FLIGHTS CASCADE CONSTRAINTS;
DROP TABLE AIRPORT CASCADE CONSTRAINTS;
DROP TABLE AIRLINE CASCADE CONSTRAINTS;

CREATE TABLE AIRPORT(
    AIRP_ID NUMBER NOT NULL PRIMARY KEY,
    AIRP_NAME VARCHAR2(100),
    AIRP_CODE VARCHAR2(3) UNIQUE,
    CITY VARCHAR2(50)
);

CREATE TABLE AIRLINE(
    AIR_ID NUMBER NOT NULL PRIMARY KEY,
    AIR_NAME VARCHAR2(100),
    AIR_CODE VARCHAR2(10) UNIQUE
);

CREATE TABLE AIRLINE_AIRPORT(
    AIRLINE_AIRPORT_ID NUMBER NOT NULL PRIMARY KEY,
    AIR_ID NUMBER NOT NULL,
    AIRP_ID NUMBER NOT NULL,
    CONSTRAINT FK_AA_AIRLINE FOREIGN KEY (AIR_ID) REFERENCES AIRLINE(AIR_ID),
    CONSTRAINT FK_AA_AIRPORT FOREIGN KEY (AIRP_ID) REFERENCES AIRPORT(AIRP_ID)
);

CREATE TABLE FLIGHTS(
    FLIGHT_ID NUMBER NOT NULL PRIMARY KEY,
    AIR_ID NUMBER NOT NULL,
    DEPART_AIRP_ID NUMBER NOT NULL,
    ARRIVAL_AIRP_ID NUMBER NOT NULL,
    FLIGHT_DATE DATE,
    FLIGHT_SCH_DEPART TIMESTAMP,
    FLIGHT_ACT_DEPART TIMESTAMP,
    FLIGHT_SCH_ARRIVAL TIMESTAMP,
    FLIGHT_ACT_ARRIVAL TIMESTAMP,
    CONSTRAINT FK_FLIGHT_AIRLINE FOREIGN KEY (AIR_ID) REFERENCES AIRLINE(AIR_ID),
    CONSTRAINT FK_FLIGHT_DEPART_AIRP FOREIGN KEY (DEPART_AIRP_ID) REFERENCES AIRPORT(AIRP_ID),
    CONSTRAINT FK_FLIGHT_ARRIVAL_AIRP FOREIGN KEY (ARRIVAL_AIRP_ID) REFERENCES AIRPORT(AIRP_ID)
);

CREATE TABLE DELAYS(
    DELAY_ID NUMBER NOT NULL PRIMARY KEY,
    FLIGHT_ID NUMBER NOT NULL,
    DELAY_REASON VARCHAR2(20),
    DELAY_MINUTES NUMBER,
    CONSTRAINT FK_DELAY_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(FLIGHT_ID)
);
